### PR TITLE
allow to fetch myfreeweb dependencies directly from GitHub

### LINKED ISSUE #4: [onboarding] let Stack fetch dependencies from GitHub?
This is very minor, but i'm somewhat obsessed with onboarding: the current `stack.yaml` references local clones of your own Haskell libraries - this only a few seconds and can be scripted, but may be further streamlined outside of development.

I imagine the local clones are used in your own development workflow. However, would it be useful for me to send a PR that keeps the current `stack.yaml` with an alternative name (say `stack-development.yaml`) and updates `stack.yaml` to fetch these packages directly from GitHub?

This way, you (and others hacking locally on sweetroll, gitson, etc.) can still iterate quickly (`stack --stack-yaml stack-development.yaml build`) whereas new users checking out sweetroll can just issue `stack build` and let Stack do all the fetching etc.

(I see that your Indieweb libraries are on Hackage too, but it seems that only the GitHub master branches have all the latest features needed for master *sweetroll*, so it's probably best not to just let Stack fetch these from Hackage as Cabal dependencies for the time being)

I may be off with my proposed solution (just starting out with Haskell/Stack etc.) - it works for me but i may be very well overcomplicating 😐

### PR DESCRIPTION
**Pull request by hotzeplotz**
This should fix #4.

Not sure why the commit from my previous PR (#3) got included in this PR: i guess i just need more Sunday morning coffee.

(I have also updated the documentation referencing `stack-dev.yaml` for local dev builds, and adding a reference to the dev package for duktape being needed for hs-duktape to be built successfully)

### CODE REVIEW

**Comment by myfreeweb** [comment]
> install the Duktape development files

No! This is not right! You might have noticed that [hs-duktape](https://github.com/myfreeweb/hs-duktape) includes duktape itself as a git submodule, and it's supposed to build from there. If it failed to build without duktape on your system, that's a bug. And a very weird bug, because hs-duktape passes tests on Travis CI without any system-wide duktape things.

(also wow, your commit messages for these trivial changes are very long and detailed, my commit message would've been just "add second stack yaml" :D)

**Comment by myfreeweb** [comment]
Wait, crap, maybe it's just because Stack doesn't fetch submodules!

**Comment by myfreeweb** [comment]
Apparently it should pull submodules https://github.com/commercialhaskell/stack/pull/1852 Is your Stack up to date?

**Comment by hotzeplotz** [comment]
you are right - Stack should be fetching submodules: i actually see in its logs that `git` is invoked with `git clone --recursive [...]` but for some reason the `duktape` folder where the submodule should be ends up being empty on my dev box. i'll have a closer look tomorrow to check why and redo the PR removing the spurious addition to documentation re installing the duktape headers.

**Comment by myfreeweb** [comment]
Closing because I'm doing some huge changes that involve getting rid of duktape altogether :)

**Pull request closed without merging**
