### PR TITLE
fix compilation error due to missing file (in missing bower dependency)

### PR DESCRIPTION
**Pull request by hotzeplotz**
this is my first attempt to build and use sweetroll (which looks awesome btw!) - i could only get this to build by adding `lazyload-image` as Bower dependency in `bower.json`.

(i am not sure whether the previous auto-commit with log message *Gitson transaction* should be included in the PR)

### CODE REVIEW

**Comment by myfreeweb** [comment]
Yeah, I forgot to add that dependency :D Thanks for your interest in sweetroll.

Delete `Gitson transaction` of course. It happened because you ran sweetroll in its source directory. It's supposed to run in your website directory. I accidentally do that sometimes lol.

Probably should add `conf/sweetroll.json` to `.gitignore` in this repo… (though won't completely help when it accidentally commits *your changes* as `Gitson transaction`)

**Comment by hotzeplotz** [comment]
ok, now i understand what the Gitson transaction is :)

(i'm still very much getting to know sweetroll and have only started learning Haskell recently so it's a slow start for me here, though i am super excited about sweetroll since i saw it mentioned (by yourself, i think) in a HN thread a couple of days ago)

ok, i rebased and deleted the alien commit and force-pushed to my fork, which seems to have removed the Gitson commit from the PR. tiny PR but hopefully helpful to others starting out with sweetroll.

(my username is not connected to ADOM - wasn't even aware of it!)

**Comment by myfreeweb** [comment]
Yep I mentioned it in the thread.

Sweetroll (and a few libraries it depends on) was my Haskell learning project :D I actually started with [gitson](https://github.com/myfreeweb/gitson). You can see that gitson's code is simpler than Sweetroll or, say, microformats2-parser.

So, getting to know Sweetroll. Your comments have inspired me to think about its structure and try to describe it here :D Here goes.

Sweetroll is roughly made of three parts: Micropub, Webmention and the website frontend. The separation is currently not very good and I just realized what I should do:

- `Auth` should be in `Micropub`, nothing else needs it, nothing else should need it. If I ever get around to, like, adding a site configuration API, it should be a Micropub extension.
- `Slice`, `Rendering`, `Pages`, most of `Api` and some of `Monads` should be extracted into a `Frontend` directory.
- there should be better separation between the three parts. Maybe not as extreme as splitting them into their own standalone services but… maybe even that, optionally.
  - But more importantly, I'm thinking there should be some kind of dependency injection-like thing instead of these parts depending directly on all the other things in sweetroll. (E.g. the `Events` functions should be injected.)
  - And like, they should have their own configs/contexts/etc. and the sweetroll config/context/etc. should be a composition of those. Kind of. They might have intersecting fields. So concern-specific config types.
  - They should have their own Servant `Routes` modules.
- (already mentioned in the readme todo) many things from `Prelude`, `HTTPClient`, maybe `Monads` should be extracted into a separate WebPrelude library.
- `Proxy` should be its own library (and executable) really. (It's like [camo](https://github.com/atmos/camo)).
- I was thinking about making an "embeddable nginx-like thing" that sets up [wai-better-cache](https://github.com/myfreeweb/wai-better-cache), [throttling](https://hackage.haskell.org/package/wai-middleware-throttle), gzip, the image `Proxy` and reverse proxies to other apps (unix sockets, tcp, cgi, etc.) based on a config. Embeddable because it should be available both as a standalone executable and as part of sweetroll (or any other app that wants to use it).
- the templating system should be its own library. With tests and benchmarks.
- I should do something with the `guardJust*`, `guardBool*` functions from my `Prelude`. They make code more compact but less obvious. Maybe they just need better names.

Gitson is really the common base for all three parts — where they *really* interact is at the storage level.

**Comment by hotzeplotz** [comment]
fantastic, thank you. still way over the top of my Haskell-beginner head, but very useful to navigate sweetroll's architecture.

**Pull request merged**
